// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_TzQKWXWiRQcFkAQktebZe4ImR5wv03U',
    appId: '1:133499258011:web:06dd9c89ab82203a17f23e',
    messagingSenderId: '133499258011',
    projectId: 'kawser-com',
    authDomain: 'kawser-com.firebaseapp.com',
    storageBucket: 'kawser-com.firebasestorage.app',
    measurementId: 'G-MYB5QN4DKS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMFiNq_YDGLeXdQeAh3NdZmdZWr6qS2o0',
    appId: '1:133499258011:android:aa0a461d98e837be17f23e',
    messagingSenderId: '133499258011',
    projectId: 'kawser-com',
    storageBucket: 'kawser-com.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBe32BRph3AS7uWjh9CSABce_WPrlLnRiM',
    appId: '1:133499258011:ios:fb50b16e798788e217f23e',
    messagingSenderId: '133499258011',
    projectId: 'kawser-com',
    storageBucket: 'kawser-com.firebasestorage.app',
    iosBundleId: 'com.example.kawser',
  );
}
